codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: '70...100'

    status:
        project:
            default: off
            app:
                flags: app
            home:
                target: 99%
                flags: home
            edition:
                target: 70%
                flags: edition
            search:
                target: 70%
                flags: search
            structure:
                target: 99%
                flags: structure
            contact:
                target: 99%
                flags: contact
        patch: yes
        changes: no

flags:
    app:
        paths:
            - app
    home:
        paths:
            - app/home/
    edition:
        paths:
            - app/edition/
    search:
        paths:
            - app/search/
    strcuture:
        paths:
            - app/structure/
    contact:
        paths:
            - app/contact/

comment:
    layout: 'reach, diff, flags, files, footer'
    behavior: default
    require_changes: no
