dist: trusty
sudo: false

language: node_js
node_js:
    - '10'

addons:
    chrome: stable

cache:
    directories:
        - ./node_modules

before_install:
    # install custom version of yarn & export executable
    # see https://yarnpkg.com/en/docs/install-ci#travis-tab
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
    - export PATH=$HOME/.yarn/bin:$PATH

install:
    - yarn install

stages:
    # test stage
    - name: test
      if: tag IS blank # exclude tags from being tested
    # deploy stage
    - name: deploy # generally, only deploy if we are on 'master'
      if: branch = master

jobs:
    include:
        - stage: test
          name: 'Unit Tests'
          script:
              # run test script
              - yarn run test:ci
          after_success:
              # run code coverage only after successful tests
              - bash <(curl -s https://codecov.io/bash)
        - stage: deploy
          name: 'Deploy to gh-pages'
          script:
              # run deploy script (only on master, see stages)
              - yarn run deploy:ci
