name: CI Workflow

on:
    [push, pull_request]:
        branches:
            - '**'    # trigger on all branches
        tags:
            - 'v*'    # trigger on all tags
        paths-ignore:
            - '**.md' # ignore changes in markdown files

jobs:
    test:
        name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [12, 14.16, 15, 16]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Run CI tests with coverage
              run: |
                  yarn run test:ci

            - name: Upload code coverage
              if: matrix.node-version == 14.16 # upload coverage report for current node version only
              uses: codecov/codecov-action@v1
              with:
                  flags: unittests
                  env_vars: ${{ matrix.os }}, ${{ matrix.node-version }}

            - name: Test build for GH Pages (Node < v16)
              if: matrix.node-version != 16
              run: |
                  yarn run build:gh

            # Workaround for build path issue with node 16:
            # https://github.com/angular/angular-cli/issues/21202
            - name: Test build for GH Pages (Node == v16)
              if: matrix.node-version == 16
              run: |
                  yarn build:prod --delete-output-path false --base-href $npm_package_homepage && yarn gzip:dist && yarn build:doc


    deploy:
        name: Deploy app from main (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        needs: test
        # run only on main
        if: github.ref == 'refs/heads/main'

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [ 14.16 ]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Build app for GH Pages
              run: |
                  yarn run build:gh

            - name: Deploy to GH Pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn run deploy:ci


    release:
        name: Create Release from tag
        runs-on: ${{ matrix.os }}
        needs: test
        # run only on tags
        if: startsWith(github.ref, 'refs/tags/')

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node-version: [ 14.16 ]

        steps:
            -   name: Get tag version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            -   name: Create Release
                id: create_release
                if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
                uses: softprops/action-gh-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    TAG_VERSION: ${{ steps.get_version.outputs.VERSION }}
                with:
                    name: Release ${{ env.TAG_VERSION }}
                    body: "A prototype web application for the online edition of the [Anton Webern Gesamtausgabe](https://www.anton-webern.ch), located at the Musicological Seminar of the University of Basel. It is written in [Angular](https://angular.io/) and runs on [edition.anton-webern.ch](https://edition.anton-webern.ch).\n\n
                    Changes since last release: https://github.com/${{ github.repository }}/blob/${{ env.TAG_VERSION }}/CHANGELOG.md"
                    draft: false
                    prerelease: false
